### ISSUE TITLE
use system version of libfreenect for kinetic ?

### ISSUE THREAD

**Issue by guihomework** [piyushk/freenect_stack#13] opened 2017-06-12 16:03 UTC
Hi, 

There is no issue reporting on https://github.com/ros-drivers/libfreenect so I guess I need to put my claim here.

as of ```xenial```, the version in the system is ```libfreenect 0.5.3```. This sentence in the wiki 
```
The main advantage of using this revision over the system package are:

    The ability to search for a Kinect through serial number, necessary for running multiple Kinects.
    USB 3.0 Support 
```

seems then outdated since the system version is higher than the one released in kinetic ```libfreenect 0.5.1```

I tested without recompiling ```freenect_camera```, dynamically linking to the system version of ```libfreenect``` and it is apparently even compatible.

The opposite is not true.

We face problems when using our own application that needs ROS for publishing data but that also uses the system ```libfreenect``` to grab kinect data. Then because ROS sets the ```LD_LIBRARY_PATH``` with ROS path before system, our app finds the ROS lib and does not like the 0.5.1

You might argue don't install ```libfreenect``` from ROS if you don't use the ROS grabber. Obviously we need the ```freenect_camera``` for some other app in the same machine. So we need to find a way to make our two apps co-exist

You might then argue again, why don't you use the ROS version in your own app (completely dropping then the system version). We also have reasons too complex to detail here, why we need the system version. So not an option.

my main question to you is why in kinetic is there a need to use the ROS (not updated since 2015) version of ```libfreenect``` when the system version has the features needed by ```freenect_camera```.

thanks

**Comment by piyushk** [comment] 2017-10-23 14:58
@guihomework: Apologies for missing this message earlier. The correct location for reporting the issue is here: https://github.com/ros-drivers/freenect_stack. This repo is deprecated.

In response to your question, the answer is there is no need to use a ros specific libfreenect anymore, although there was a need in the past. 

I no longer actively main freenect_stack, and consequently it has not seen a lot of updates since. Any help on resolving this issue will be appreciated, although it'll be hard getting changes in Kinetic without affecting legacy behavior users expect. Implementing a change in ROS Lunar should be possible.

If this is still a problem, please reopen the issue there!

**Closed as completed by piyushk** 2017-10-23 14:58 UTC
